language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - jruby
  - rbx-2
gemfile:
  - gemfiles/Gemfile.sidekiq-2
  - Gemfile
before_install:
  - gem update --system
  - gem update bundler
services: redis
matrix:
  allow_failures:
    - rvm: jruby
    - rvm: rbx-2
